### ISSUE TITLE
如何将lxcfs的deamonset和deployment都部署在指定的namaspace中？

### ISSUE THREAD

**Issue by xbw1220** [denverdino/lxcfs-admission-webhook#20]
如何将lxcfs的deamonset和deployment都部署在指定的namaspace中？
修改了部署的脚本发现指定命名空间部署后不生效了

**Comment by arsenalpoll** [comment]
改yaml文件无效吗？ 里面加指定ns

**Comment by xbw1220** [comment]
后来仔细看了一些shell脚本把里面的默认命名空间指定为自己需要的命名空间，其他的对应的也加上命名空间后也可以了
