### ISSUE TITLE
lxcfs 是不是不支持 Alpine Linux 系统吗?

### ISSUE THREAD

**Issue by yangpeng14** [denverdino/lxcfs-admission-webhook#7]
lxcfs 是不是不支持 Alpine Linux 系统，在使用 Alpine Linux 3.11 部署pod，通过  free -m 显示的内存并不是 limits 设置的大小，而宿主机系统内存

**Comment by denverdino** [comment]
嗯，Alpine没有glibc，musl很多实现不同

**Comment by yangpeng14** [comment]
> 嗯，Alpine没有glibc，musl很多实现不同

好的，谢谢
